<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            // Core Administration
            'manage companies',
            'manage branches',
            'manage departments',
            'manage users',
            'manage roles',
            'manage permissions',
            'manage patients',

            // Patient — the plural `patients.*` convention is the one actually enforced by
            // PatientPolicy/modules/Patients routes; a legacy singular `patient.*` set used to
            // coexist unused (dead permissions nothing checked) and has been removed.
            'patients.view',
            'patients.create',
            'patients.update',
            'patients.delete',
            'patients.merge',
            'patients.export',
            'patients.print',
            'patients.alert.view',
            'patients.alert.manage',
            'patients.documents.view',
            'patients.documents.manage',
            'patients.consents.view',
            'patients.consents.manage',
            'patients.amend.request',
            'patients.amend.approve',
            'patients.portal.manage',

            // Appointment — plural `appointments.*` is the convention actually enforced by
            // AppointmentPolicy/modules/Appointments routes; a legacy singular `appointment.*`
            // set used to coexist unused (dead permissions nothing checked, the same pattern
            // already found and removed for patients) and has been removed.
            'appointments.view',
            'appointments.create',
            'appointments.update',
            'appointments.delete',
            'appointments.confirm',
            'appointments.checkin',
            'appointments.cancel',
            'appointments.reschedule',
            'appointments.no_show',
            'appointments.queue',
            'appointments.token',
            'appointments.override',
            'appointments.export',
            'appointments.print',
            'appointments.manage_schedule',
            'appointments.manage_provider',
            'appointments.manage_holiday',
            'appointments.manage_block',
            'appointments.manage_overbooking',

            // Doctor Schedules
            'schedules.view',
            'schedules.create',
            'schedules.update',
            'schedules.delete',

            // Queue
            'queue.view',
            'queue.manage',

            // OPD
            'opd.view',
            'opd.create',
            'opd.update',
            'opd.consult',

            // Emergency
            'emergency.view',
            'emergency.create',
            'emergency.update',
            'emergency.triage',

            // IPD
            'ipd.view',
            'ipd.create',
            'ipd.update',
            'ipd.admit',
            'ipd.discharge',

            // Bed Management
            'bed.view',
            'bed.allocate',
            'bed.transfer',
            'bed.block',

            // Nursing
            'nursing.view',
            'nursing.create',
            'nursing.update',
            'nursing.administer',

            // Doctor/Physician
            'doctor.view',
            'doctor.create',
            'doctor.update',
            'doctor.consult',

            // EMR
            'emr.view',
            'emr.create',
            'emr.update',
            'emr.amend',
            'emr.approve',

            // Encounter
            'encounters.view',
            'encounters.create',
            'encounters.update',
            'encounters.delete',
            'encounter.start',
            'encounter.complete',
            'encounter.cancel',
            'encounter.amend',
            'encounter.lock',
            'encounter.export',
            'encounter.print',

            // Clinical
            'clinical.note.view',
            'clinical.note.create',
            'clinical.note.update',
            'clinical.vitals.view',
            'clinical.vitals.create',
            'clinical.diagnosis.view',
            'clinical.diagnosis.create',
            'clinical.diagnosis.update',
            'clinical.order.view',
            'clinical.order.create',
            'clinical.order.cancel',
            'clinical.referral.view',
            'clinical.referral.create',
            'clinical.break_glass',

            // Prescription
            'prescription.view',
            'prescription.create',
            'prescription.update',
            'prescription.issue',
            'prescription.cancel',
            'prescription.amend',

            // Pharmacy
            'pharmacy.view',
            'pharmacy.create',
            'pharmacy.update',
            'pharmacy.dispense',
            'pharmacy.adjust',

            // Laboratory
            'laboratory.view',
            'laboratory.create',
            'laboratory.update',
            'laboratory.verify',
            'laboratory.approve',
            'laboratory.release',

            // Radiology
            'radiology.view',
            'radiology.create',
            'radiology.update',
            'radiology.report',

            // OT
            'ot.view',
            'ot.create',
            'ot.update',
            'ot.schedule',

            // ICU
            'icu.view',
            'icu.create',
            'icu.update',

            // Billing
            'billing.view',
            'billing.create',
            'billing.update',
            'billing.discount',
            'billing.refund',
            'billing.payment',

            // Billing — Phase 4
            'billing.dashboard.view',
            'billing.charge.view',
            'billing.charge.create',
            'billing.charge.cancel',
            'billing.invoice.view',
            'billing.invoice.create',
            'billing.invoice.update',
            'billing.invoice.finalize',
            'billing.invoice.cancel',
            'billing.invoice.writeoff',
            'billing.payment.view',
            'billing.payment.create',
            'billing.payment.cancel',
            'billing.receipt.view',
            'billing.receipt.void',
            'billing.refund.request',
            'billing.refund.approve',
            'billing.refund.process',
            'billing.adjustment.request',
            'billing.adjustment.approve',
            'billing.cashier.open',
            'billing.cashier.close',
            'billing.cashier.view',
            'billing.cashier.reconcile',
            'billing.pricing.view',
            'billing.pricing.manage',
            'billing.category.manage',
            'billing.item.manage',
            'billing.corporate.view',
            'billing.corporate.manage',
            'billing.insurance.policy.view',
            'billing.insurance.policy.manage',
            'billing.report.view',
            'billing.settings.manage',

            // Laboratory — Phase 5
            'lab.dashboard.view',
            'lab.test.view',
            'lab.test.create',
            'lab.test.update',
            'lab.panel.view',
            'lab.panel.create',
            'lab.panel.update',
            'lab.specimen.view',
            'lab.specimen.collect',
            'lab.specimen.receive',
            'lab.specimen.reject',
            'lab.specimen.process',
            'lab.order.view',
            'lab.order.create',
            'lab.order.cancel',
            'lab.result.view',
            'lab.result.create',
            'lab.result.update',
            'lab.result.validate',
            'lab.result.approve',
            'lab.result.amend',
            'lab.report.view',
            'lab.report.generate',
            'lab.report.print',
            'lab.report.export',
            'lab.critical_result.view',
            'lab.critical_result.notify',
            'lab.critical_result.acknowledge',
            'lab.qc.view',
            'lab.qc.create',
            'lab.analyzer.view',
            'lab.analyzer.configure',
            'lab.settings.manage',

            // Radiology — Phase 6
            'radiology.dashboard.view',
            'radiology.procedure.view',
            'radiology.procedure.create',
            'radiology.procedure.update',
            'radiology.modality.view',
            'radiology.modality.create',
            'radiology.modality.update',
            'radiology.order.view',
            'radiology.order.create',
            'radiology.order.cancel',
            'radiology.schedule.view',
            'radiology.schedule.create',
            'radiology.schedule.update',
            'radiology.schedule.cancel',
            'radiology.examination.view',
            'radiology.examination.start',
            'radiology.examination.complete',
            'radiology.study.view',
            'radiology.study.export',
            'radiology.worklist.view',
            'radiology.worklist.assign',
            'radiology.report.view',
            'radiology.report.create',
            'radiology.report.update',
            'radiology.report.submit',
            'radiology.report.approve',
            'radiology.report.amend',
            'radiology.critical_finding.view',
            'radiology.critical_finding.create',
            'radiology.critical_finding.notify',
            'radiology.critical_finding.acknowledge',
            'radiology.pacs.view',
            'radiology.pacs.manage',
            'radiology.dicom.view',
            'radiology.dicom.manage',
            'radiology.settings.manage',

            // Pharmacy — Phase 7
            'pharmacy.dashboard.view',
            'pharmacy.medication.view',
            'pharmacy.medication.create',
            'pharmacy.medication.update',
            'pharmacy.generic.view',
            'pharmacy.generic.create',
            'pharmacy.generic.update',
            'pharmacy.brand.view',
            'pharmacy.brand.create',
            'pharmacy.brand.update',
            'pharmacy.prescription.view',
            'pharmacy.prescription.review',
            'pharmacy.dispensing.view',
            'pharmacy.dispensing.create',
            'pharmacy.dispensing.verify',
            'pharmacy.dispensing.cancel',
            'pharmacy.dispensing.return',
            'pharmacy.stock.view',
            'pharmacy.stock.receive',
            'pharmacy.stock.transfer',
            'pharmacy.stock.adjust',
            'pharmacy.stock.count',
            'pharmacy.batch.view',
            'pharmacy.batch.create',
            'pharmacy.batch.update',
            'pharmacy.expiry.view',
            'pharmacy.quarantine.manage',
            'pharmacy.substitution.view',
            'pharmacy.substitution.approve',
            'pharmacy.safety_alert.view',
            'pharmacy.safety_alert.override',
            'pharmacy.controlled_drug.view',
            'pharmacy.controlled_drug.manage',
            'pharmacy.recall.view',
            'pharmacy.recall.manage',
            'pharmacy.reports.view',
            'pharmacy.reports.export',
            'pharmacy.settings.manage',

            // IPD — Phase 8
            'ipd.dashboard.view',
            'ipd.admission.view',
            'ipd.admission.create',
            'ipd.admission.update',
            'ipd.admission.approve',
            'ipd.admission.cancel',
            'ipd.ward.view',
            'ipd.ward.create',
            'ipd.ward.update',
            'ipd.room.view',
            'ipd.room.create',
            'ipd.room.update',
            'ipd.bed.view',
            'ipd.bed.create',
            'ipd.bed.update',
            'ipd.bed.block',
            'ipd.bed.unblock',
            'ipd.bed.reserve',
            'ipd.bed.allocate',
            'ipd.bed.release',
            'ipd.transfer.view',
            'ipd.transfer.create',
            'ipd.transfer.approve',
            'ipd.transfer.complete',
            'ipd.transfer.cancel',
            'ipd.discharge.view',
            'ipd.discharge.create',
            'ipd.discharge.approve',
            'ipd.discharge.complete',
            'ipd.leave.view',
            'ipd.leave.create',
            'ipd.leave.approve',
            'ipd.leave.complete',
            'ipd.reports.view',
            'ipd.reports.export',
            'ipd.settings.manage',
            'ipd.audit.view',

            // Insurance
            'insurance.view',
            'insurance.create',
            'insurance.update',
            'insurance.submit',
            'insurance.approve',

            // Finance
            'finance.view',
            'finance.create',
            'finance.update',
            'finance.post',
            'finance.close',

            // Inventory
            'inventory.view',
            'inventory.create',
            'inventory.update',
            'inventory.adjust',
            'inventory.transfer',

            // Procurement
            'procurement.view',
            'procurement.create',
            'procurement.update',
            'procurement.approve',

            // HR
            'hr.view',
            'hr.create',
            'hr.update',
            'hr.attendance',
            'hr.payroll',

            // Reporting
            'reporting.view',
            'reporting.export',
            'reporting.print',

            // Audit
            'audit.view',

            // Activity
            'activity.view',
            'activity.export',

            // Security
            'security.event.view',
            'security.event.resolve',
            'login.history.view',

            // System
            'system.health.view',
            'system.queue.view',
            'system.scheduler.view',

            // Workflow
            'workflow.view',
            'workflow.act',
            'workflow.manage',

            // Settings
            'settings.view',
            'settings.update',

            // Notifications
            'notification.view',
            'notification.manage',

            // Files
            'file.view',
            'file.manage',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        // Create default roles
        $roles = [
            'super_admin' => $permissions,
            'hospital_admin' => [
                'manage companies', 'manage branches', 'manage departments', 'manage users', 'manage patients',
                'patients.view', 'patients.create', 'patients.update', 'patients.delete', 'patients.merge', 'patients.export', 'patients.print',
                'patients.alert.view', 'patients.alert.manage', 'patients.documents.view', 'patients.documents.manage',
                'patients.consents.view', 'patients.consents.manage', 'patients.amend.request', 'patients.amend.approve', 'patients.portal.manage',
                'appointments.view', 'appointments.create', 'appointments.update', 'appointments.delete',
                'appointments.confirm', 'appointments.checkin', 'appointments.cancel', 'appointments.reschedule', 'appointments.no_show',
                'appointments.queue', 'appointments.token', 'appointments.override', 'appointments.export', 'appointments.print',
                'appointments.manage_schedule', 'appointments.manage_provider', 'appointments.manage_holiday',
                'appointments.manage_block', 'appointments.manage_overbooking',
                'schedules.view', 'schedules.create', 'schedules.update', 'schedules.delete',
                'queue.view', 'queue.manage',
                'opd.view', 'opd.create', 'opd.update', 'opd.consult',
                'encounters.view', 'encounters.create', 'encounters.update', 'encounters.delete',
                'encounter.start', 'encounter.complete', 'encounter.cancel', 'encounter.amend',
                'encounter.lock', 'encounter.export', 'encounter.print',
                'clinical.note.view', 'clinical.note.create', 'clinical.note.update',
                'clinical.vitals.view', 'clinical.vitals.create',
                'clinical.diagnosis.view', 'clinical.diagnosis.create', 'clinical.diagnosis.update',
                'clinical.order.view', 'clinical.order.create', 'clinical.order.cancel',
                'clinical.referral.view', 'clinical.referral.create',
                'clinical.break_glass',
                'prescription.view', 'prescription.create', 'prescription.update', 'prescription.issue', 'prescription.cancel', 'prescription.amend',
                'billing.view', 'billing.create', 'billing.update', 'billing.payment',
                'billing.dashboard.view', 'billing.invoice.view', 'billing.invoice.finalize', 'billing.invoice.cancel', 'billing.invoice.writeoff',
                'billing.refund.approve', 'billing.adjustment.approve',
                'billing.pricing.view', 'billing.pricing.manage', 'billing.category.manage', 'billing.item.manage', 'billing.settings.manage',
                'billing.corporate.view', 'billing.corporate.manage',
                'billing.insurance.policy.view', 'billing.insurance.policy.manage',
                'billing.report.view',
                'lab.dashboard.view', 'lab.test.view', 'lab.test.create', 'lab.test.update',
                'lab.panel.view', 'lab.panel.create', 'lab.panel.update',
                'lab.order.view', 'lab.order.cancel',
                'lab.result.view', 'lab.result.approve', 'lab.result.amend',
                'lab.report.view', 'lab.report.export',
                'lab.critical_result.view',
                'lab.qc.view', 'lab.analyzer.view', 'lab.analyzer.configure', 'lab.settings.manage',
                'radiology.dashboard.view', 'radiology.procedure.view', 'radiology.procedure.create', 'radiology.procedure.update',
                'radiology.modality.view', 'radiology.modality.create', 'radiology.modality.update',
                'radiology.order.view', 'radiology.order.cancel',
                'radiology.report.view', 'radiology.report.approve', 'radiology.report.amend',
                'radiology.critical_finding.view',
                'radiology.pacs.view', 'radiology.pacs.manage', 'radiology.dicom.view', 'radiology.dicom.manage', 'radiology.settings.manage',
                'pharmacy.dashboard.view', 'pharmacy.medication.view', 'pharmacy.medication.create', 'pharmacy.medication.update',
                'pharmacy.generic.view', 'pharmacy.generic.create', 'pharmacy.generic.update',
                'pharmacy.brand.view', 'pharmacy.brand.create', 'pharmacy.brand.update',
                'pharmacy.dispensing.view', 'pharmacy.stock.view', 'pharmacy.batch.view', 'pharmacy.expiry.view',
                'pharmacy.quarantine.manage', 'pharmacy.substitution.view', 'pharmacy.substitution.approve',
                'pharmacy.safety_alert.view', 'pharmacy.safety_alert.override',
                'pharmacy.controlled_drug.view', 'pharmacy.controlled_drug.manage',
                'pharmacy.recall.view', 'pharmacy.recall.manage',
                'pharmacy.reports.view', 'pharmacy.settings.manage',
                'ipd.dashboard.view',
                'ipd.admission.view', 'ipd.admission.create', 'ipd.admission.update', 'ipd.admission.approve', 'ipd.admission.cancel',
                'ipd.ward.view', 'ipd.ward.create', 'ipd.ward.update',
                'ipd.room.view', 'ipd.room.create', 'ipd.room.update',
                'ipd.bed.view', 'ipd.bed.create', 'ipd.bed.update', 'ipd.bed.block', 'ipd.bed.unblock',
                'ipd.bed.reserve', 'ipd.bed.allocate', 'ipd.bed.release',
                'ipd.transfer.view', 'ipd.transfer.create', 'ipd.transfer.approve', 'ipd.transfer.complete', 'ipd.transfer.cancel',
                'ipd.discharge.view', 'ipd.discharge.create', 'ipd.discharge.approve', 'ipd.discharge.complete',
                'ipd.leave.view', 'ipd.leave.create', 'ipd.leave.approve', 'ipd.leave.complete',
                'ipd.reports.view', 'ipd.reports.export', 'ipd.settings.manage', 'ipd.audit.view',
                'reporting.view', 'reporting.export', 'reporting.print',
                'settings.view',
                'workflow.view', 'workflow.act', 'workflow.manage',
            ],
            'doctor' => [
                'patients.view', 'patients.create', 'patients.update',
                'patients.alert.view', 'patients.alert.manage', 'patients.documents.view', 'patients.documents.manage',
                'patients.consents.view', 'patients.amend.request',
                'appointments.view', 'appointments.create', 'appointments.update', 'appointments.cancel',
                'appointments.confirm', 'appointments.checkin', 'appointments.reschedule', 'appointments.no_show', 'appointments.queue',
                'opd.view', 'opd.create', 'opd.update', 'opd.consult',
                'emr.view', 'emr.create', 'emr.update', 'emr.amend', 'emr.approve',
                'encounters.view', 'encounters.create', 'encounters.update',
                'encounter.start', 'encounter.complete', 'encounter.cancel', 'encounter.amend',
                'encounter.lock', 'encounter.export', 'encounter.print',
                'clinical.note.view', 'clinical.note.create', 'clinical.note.update',
                'clinical.vitals.view', 'clinical.vitals.create',
                'clinical.diagnosis.view', 'clinical.diagnosis.create', 'clinical.diagnosis.update',
                'clinical.order.view', 'clinical.order.create', 'clinical.order.cancel',
                'clinical.referral.view', 'clinical.referral.create',
                'prescription.view', 'prescription.create', 'prescription.update', 'prescription.issue', 'prescription.cancel', 'prescription.amend',
                'laboratory.view', 'laboratory.create', 'laboratory.update',
                'lab.dashboard.view', 'lab.order.view', 'lab.order.create', 'lab.order.cancel',
                'lab.result.view', 'lab.report.view', 'lab.report.print',
                'lab.critical_result.view', 'lab.critical_result.acknowledge',
                'radiology.view', 'radiology.create', 'radiology.update', 'radiology.report',
                'radiology.dashboard.view', 'radiology.order.view', 'radiology.order.create', 'radiology.order.cancel',
                'radiology.report.view', 'radiology.critical_finding.view', 'radiology.critical_finding.acknowledge',
                'pharmacy.dashboard.view', 'pharmacy.prescription.view', 'pharmacy.dispensing.view', 'pharmacy.safety_alert.view',
                'ipd.dashboard.view',
                'ipd.admission.view', 'ipd.admission.create',
                'ipd.bed.view',
                'ipd.transfer.view', 'ipd.transfer.create',
                'ipd.discharge.view', 'ipd.discharge.create', 'ipd.discharge.approve',
                'ipd.leave.view', 'ipd.leave.approve',
                'reporting.view',
            ],
            'nurse' => [
                'patients.view', 'patients.alert.view', 'patients.documents.view',
                'nursing.view', 'nursing.create', 'nursing.update', 'nursing.administer',
                'emr.view', 'emr.create', 'emr.update',
                'encounters.view', 'encounters.update', 'encounter.start',
                'clinical.note.view', 'clinical.note.create',
                'clinical.vitals.view', 'clinical.vitals.create',
                'clinical.diagnosis.view',
                'prescription.view',
                'ipd.dashboard.view', 'ipd.admission.view',
                'ipd.bed.view',
                'ipd.transfer.view', 'ipd.transfer.create',
                'ipd.leave.view', 'ipd.leave.create', 'ipd.leave.complete',
                'reporting.view',
            ],
            'receptionist' => [
                'patients.view', 'patients.create', 'patients.update', 'patients.print',
                'patients.documents.view', 'patients.documents.manage', 'patients.consents.view', 'patients.consents.manage',
                'appointments.view', 'appointments.create', 'appointments.update',
                'appointments.confirm', 'appointments.checkin', 'appointments.cancel', 'appointments.reschedule', 'appointments.no_show',
                'appointments.queue', 'appointments.token', 'appointments.print',
                'schedules.view',
                'queue.view', 'queue.manage',
                'billing.view', 'billing.create', 'billing.update', 'billing.payment',
                'reporting.view',
            ],
            'lab_technician' => [
                'laboratory.view', 'laboratory.create', 'laboratory.update', 'laboratory.verify',
                'lab.dashboard.view', 'lab.test.view', 'lab.panel.view',
                'lab.order.view', 'lab.specimen.view', 'lab.specimen.collect', 'lab.specimen.receive',
                'lab.specimen.reject', 'lab.specimen.process',
                'lab.result.view', 'lab.result.create', 'lab.result.update',
                'lab.report.view', 'lab.report.print',
                'lab.critical_result.view', 'lab.critical_result.notify',
                'lab.qc.view', 'lab.qc.create',
                'reporting.view',
            ],
            'senior_lab_technician' => [
                'laboratory.view', 'laboratory.create', 'laboratory.update', 'laboratory.verify',
                'lab.dashboard.view', 'lab.test.view', 'lab.panel.view',
                'lab.order.view', 'lab.specimen.view', 'lab.specimen.collect', 'lab.specimen.receive',
                'lab.specimen.reject', 'lab.specimen.process',
                'lab.result.view', 'lab.result.create', 'lab.result.update', 'lab.result.validate',
                'lab.report.view', 'lab.report.print',
                'lab.critical_result.view', 'lab.critical_result.notify', 'lab.critical_result.acknowledge',
                'lab.qc.view', 'lab.qc.create',
                'reporting.view',
            ],
            'pathologist' => [
                'laboratory.view', 'laboratory.verify', 'laboratory.approve', 'laboratory.release',
                'lab.dashboard.view', 'lab.test.view', 'lab.panel.view',
                'lab.order.view', 'lab.specimen.view',
                'lab.result.view', 'lab.result.validate', 'lab.result.approve', 'lab.result.amend',
                'lab.report.view', 'lab.report.generate', 'lab.report.print', 'lab.report.export',
                'lab.critical_result.view', 'lab.critical_result.notify', 'lab.critical_result.acknowledge',
                'lab.qc.view',
                'reporting.view',
            ],
            'lab_receptionist' => [
                'patients.view',
                'appointments.view',
                'lab.dashboard.view', 'lab.order.view', 'lab.order.create',
                'lab.specimen.view',
                'billing.view', 'billing.charge.view', 'billing.invoice.view',
                'reporting.view',
            ],
            'phlebotomist' => [
                'lab.dashboard.view', 'lab.order.view',
                'lab.specimen.view', 'lab.specimen.collect',
                'reporting.view',
            ],
            'lab_manager' => [
                'laboratory.view', 'laboratory.create', 'laboratory.update', 'laboratory.verify', 'laboratory.approve', 'laboratory.release',
                'lab.dashboard.view', 'lab.test.view', 'lab.test.create', 'lab.test.update',
                'lab.panel.view', 'lab.panel.create', 'lab.panel.update',
                'lab.order.view', 'lab.order.create', 'lab.order.cancel',
                'lab.specimen.view', 'lab.specimen.collect', 'lab.specimen.receive', 'lab.specimen.reject', 'lab.specimen.process',
                'lab.result.view', 'lab.result.create', 'lab.result.update', 'lab.result.validate', 'lab.result.approve', 'lab.result.amend',
                'lab.report.view', 'lab.report.generate', 'lab.report.print', 'lab.report.export',
                'lab.critical_result.view', 'lab.critical_result.notify', 'lab.critical_result.acknowledge',
                'lab.qc.view', 'lab.qc.create',
                'lab.analyzer.view', 'lab.analyzer.configure', 'lab.settings.manage',
                'reporting.view', 'reporting.export', 'reporting.print',
            ],
            'radiology_receptionist' => [
                'patients.view',
                'appointments.view',
                'radiology.dashboard.view', 'radiology.order.view', 'radiology.order.create',
                'radiology.schedule.view', 'radiology.schedule.create', 'radiology.schedule.update', 'radiology.schedule.cancel',
                'billing.view', 'billing.charge.view', 'billing.invoice.view',
                'reporting.view',
            ],
            'radiology_technician' => [
                'radiology.dashboard.view',
                'radiology.order.view',
                'radiology.schedule.view',
                'radiology.examination.view', 'radiology.examination.start', 'radiology.examination.complete',
                'radiology.study.view',
                'radiology.worklist.view',
                'radiology.report.view',
                'reporting.view',
            ],
            'radiologist' => [
                'radiology.view', 'radiology.report',
                'radiology.dashboard.view',
                'radiology.order.view',
                'radiology.examination.view',
                'radiology.study.view',
                'radiology.worklist.view', 'radiology.worklist.assign',
                'radiology.report.view', 'radiology.report.create', 'radiology.report.update', 'radiology.report.submit',
                'radiology.critical_finding.view', 'radiology.critical_finding.create', 'radiology.critical_finding.notify', 'radiology.critical_finding.acknowledge',
                'reporting.view',
            ],
            'senior_radiologist' => [
                'radiology.view', 'radiology.report',
                'radiology.dashboard.view',
                'radiology.order.view',
                'radiology.examination.view',
                'radiology.study.view',
                'radiology.worklist.view', 'radiology.worklist.assign',
                'radiology.report.view', 'radiology.report.create', 'radiology.report.update', 'radiology.report.submit', 'radiology.report.approve', 'radiology.report.amend',
                'radiology.critical_finding.view', 'radiology.critical_finding.create', 'radiology.critical_finding.notify', 'radiology.critical_finding.acknowledge',
                'reporting.view', 'reporting.export',
            ],
            'radiology_manager' => [
                'radiology.view', 'radiology.create', 'radiology.update', 'radiology.report',
                'radiology.dashboard.view',
                'radiology.procedure.view', 'radiology.procedure.create', 'radiology.procedure.update',
                'radiology.modality.view', 'radiology.modality.create', 'radiology.modality.update',
                'radiology.order.view', 'radiology.order.create', 'radiology.order.cancel',
                'radiology.schedule.view', 'radiology.schedule.create', 'radiology.schedule.update', 'radiology.schedule.cancel',
                'radiology.examination.view', 'radiology.examination.start', 'radiology.examination.complete',
                'radiology.study.view', 'radiology.study.export',
                'radiology.worklist.view', 'radiology.worklist.assign',
                'radiology.report.view', 'radiology.report.create', 'radiology.report.update', 'radiology.report.submit', 'radiology.report.approve', 'radiology.report.amend',
                'radiology.critical_finding.view', 'radiology.critical_finding.create', 'radiology.critical_finding.notify', 'radiology.critical_finding.acknowledge',
                'radiology.pacs.view', 'radiology.pacs.manage', 'radiology.dicom.view', 'radiology.dicom.manage', 'radiology.settings.manage',
                'reporting.view', 'reporting.export', 'reporting.print',
            ],
            'pacs_administrator' => [
                'radiology.dashboard.view',
                'radiology.study.view',
                'radiology.pacs.view', 'radiology.pacs.manage',
                'radiology.dicom.view', 'radiology.dicom.manage',
                'reporting.view',
            ],
            'pharmacy_receptionist' => [
                'pharmacy.dashboard.view',
                'pharmacy.prescription.view',
                'pharmacy.medication.view', 'pharmacy.generic.view', 'pharmacy.brand.view',
                'reporting.view',
            ],
            'pharmacy_technician' => [
                'pharmacy.dashboard.view',
                'pharmacy.medication.view', 'pharmacy.generic.view', 'pharmacy.brand.view',
                'pharmacy.prescription.view',
                'pharmacy.dispensing.view', 'pharmacy.dispensing.create',
                'pharmacy.stock.view', 'pharmacy.batch.view', 'pharmacy.expiry.view',
                'pharmacy.safety_alert.view',
                'reporting.view',
            ],
            'pharmacist' => [
                'pharmacy.view', 'pharmacy.create', 'pharmacy.update', 'pharmacy.dispense', 'pharmacy.adjust',
                'pharmacy.dashboard.view',
                'pharmacy.medication.view', 'pharmacy.generic.view', 'pharmacy.brand.view',
                'prescription.view',
                'pharmacy.prescription.view', 'pharmacy.prescription.review',
                'pharmacy.dispensing.view', 'pharmacy.dispensing.create', 'pharmacy.dispensing.verify', 'pharmacy.dispensing.cancel', 'pharmacy.dispensing.return',
                'pharmacy.stock.view', 'pharmacy.batch.view', 'pharmacy.expiry.view',
                'pharmacy.quarantine.manage',
                'pharmacy.substitution.view',
                'pharmacy.safety_alert.view', 'pharmacy.safety_alert.override',
                'pharmacy.controlled_drug.view',
                'pharmacy.reports.view',
                'reporting.view',
            ],
            'senior_pharmacist' => [
                'pharmacy.dashboard.view',
                'pharmacy.medication.view', 'pharmacy.generic.view', 'pharmacy.brand.view',
                'prescription.view',
                'pharmacy.prescription.view', 'pharmacy.prescription.review',
                'pharmacy.dispensing.view', 'pharmacy.dispensing.create', 'pharmacy.dispensing.verify', 'pharmacy.dispensing.cancel', 'pharmacy.dispensing.return',
                'pharmacy.stock.view', 'pharmacy.batch.view', 'pharmacy.expiry.view',
                'pharmacy.quarantine.manage',
                'pharmacy.substitution.view', 'pharmacy.substitution.approve',
                'pharmacy.safety_alert.view', 'pharmacy.safety_alert.override',
                'pharmacy.controlled_drug.view', 'pharmacy.controlled_drug.manage',
                'pharmacy.recall.view',
                'pharmacy.reports.view', 'pharmacy.reports.export',
                'reporting.view', 'reporting.export',
            ],
            'pharmacy_manager' => [
                'pharmacy.dashboard.view',
                'pharmacy.medication.view', 'pharmacy.medication.create', 'pharmacy.medication.update',
                'pharmacy.generic.view', 'pharmacy.generic.create', 'pharmacy.generic.update',
                'pharmacy.brand.view', 'pharmacy.brand.create', 'pharmacy.brand.update',
                'prescription.view',
                'pharmacy.prescription.view', 'pharmacy.prescription.review',
                'pharmacy.dispensing.view', 'pharmacy.dispensing.create', 'pharmacy.dispensing.verify', 'pharmacy.dispensing.cancel', 'pharmacy.dispensing.return',
                'pharmacy.stock.view', 'pharmacy.stock.receive', 'pharmacy.stock.transfer', 'pharmacy.stock.adjust', 'pharmacy.stock.count',
                'pharmacy.batch.view', 'pharmacy.batch.create', 'pharmacy.batch.update',
                'pharmacy.expiry.view',
                'pharmacy.quarantine.manage',
                'pharmacy.substitution.view', 'pharmacy.substitution.approve',
                'pharmacy.safety_alert.view', 'pharmacy.safety_alert.override',
                'pharmacy.controlled_drug.view', 'pharmacy.controlled_drug.manage',
                'pharmacy.recall.view', 'pharmacy.recall.manage',
                'pharmacy.reports.view', 'pharmacy.reports.export',
                'pharmacy.settings.manage',
                'reporting.view', 'reporting.export', 'reporting.print',
            ],
            'storekeeper' => [
                'pharmacy.dashboard.view',
                'pharmacy.medication.view', 'pharmacy.generic.view', 'pharmacy.brand.view',
                'pharmacy.stock.view', 'pharmacy.stock.receive', 'pharmacy.stock.transfer', 'pharmacy.stock.adjust', 'pharmacy.stock.count',
                'pharmacy.batch.view', 'pharmacy.batch.create', 'pharmacy.batch.update',
                'pharmacy.expiry.view',
                'pharmacy.quarantine.manage',
                'reporting.view',
            ],
            'pharmacy_administrator' => [
                'pharmacy.dashboard.view',
                'pharmacy.medication.view', 'pharmacy.medication.create', 'pharmacy.medication.update',
                'pharmacy.generic.view', 'pharmacy.generic.create', 'pharmacy.generic.update',
                'pharmacy.brand.view', 'pharmacy.brand.create', 'pharmacy.brand.update',
                'pharmacy.stock.view', 'pharmacy.batch.view',
                'pharmacy.expiry.view', 'pharmacy.quarantine.manage',
                'pharmacy.controlled_drug.view', 'pharmacy.controlled_drug.manage',
                'pharmacy.recall.view', 'pharmacy.recall.manage',
                'pharmacy.safety_alert.view',
                'pharmacy.reports.view', 'pharmacy.reports.export',
                'pharmacy.settings.manage',
                'reporting.view', 'reporting.export', 'reporting.print',
            ],
            'cashier' => [
                'billing.view', 'billing.create', 'billing.update', 'billing.payment',
                'billing.dashboard.view', 'billing.charge.view', 'billing.invoice.view',
                'billing.payment.view', 'billing.payment.create', 'billing.receipt.view',
                'billing.refund.request',
                'billing.cashier.open', 'billing.cashier.close', 'billing.cashier.view',
                'reporting.view',
            ],
            'accountant' => [
                'finance.view', 'finance.create', 'finance.update', 'finance.post', 'finance.close',
                'billing.view', 'billing.update',
                'billing.dashboard.view', 'billing.invoice.view', 'billing.payment.view', 'billing.receipt.view',
                'billing.refund.approve', 'billing.adjustment.approve',
                'billing.cashier.view', 'billing.cashier.reconcile',
                'billing.corporate.view', 'billing.insurance.policy.view',
                'billing.report.view',
                'reporting.view', 'reporting.export', 'reporting.print',
                'workflow.view', 'workflow.act',
            ],
            'admission_officer' => [
                'patients.view', 'patients.create', 'patients.update',
                'patients.documents.view',
                'ipd.dashboard.view',
                'ipd.admission.view', 'ipd.admission.create', 'ipd.admission.update', 'ipd.admission.cancel',
                'ipd.bed.view', 'ipd.bed.reserve',
                'ipd.reports.view',
                'reporting.view',
            ],
            'ipd_coordinator' => [
                'patients.view',
                'ipd.dashboard.view',
                'ipd.admission.view', 'ipd.admission.create', 'ipd.admission.update', 'ipd.admission.approve', 'ipd.admission.cancel',
                'ipd.ward.view', 'ipd.room.view',
                'ipd.bed.view', 'ipd.bed.reserve', 'ipd.bed.allocate', 'ipd.bed.release',
                'ipd.transfer.view', 'ipd.transfer.create', 'ipd.transfer.approve', 'ipd.transfer.complete', 'ipd.transfer.cancel',
                'ipd.discharge.view', 'ipd.discharge.create', 'ipd.discharge.approve', 'ipd.discharge.complete',
                'ipd.leave.view', 'ipd.leave.create', 'ipd.leave.approve', 'ipd.leave.complete',
                'ipd.reports.view', 'ipd.reports.export',
                'reporting.view', 'reporting.export',
            ],
            'ward_manager' => [
                'patients.view',
                'ipd.dashboard.view',
                'ipd.ward.view', 'ipd.ward.create', 'ipd.ward.update',
                'ipd.room.view', 'ipd.room.create', 'ipd.room.update',
                'ipd.bed.view', 'ipd.bed.create', 'ipd.bed.update', 'ipd.bed.block', 'ipd.bed.unblock',
                'ipd.bed.reserve', 'ipd.bed.allocate', 'ipd.bed.release',
                'ipd.transfer.view', 'ipd.transfer.create', 'ipd.transfer.approve', 'ipd.transfer.complete',
                'ipd.admission.view',
                'ipd.reports.view',
                'reporting.view',
            ],
        ];

        foreach ($roles as $roleName => $rolePermissions) {
            $role = Role::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
            $role->syncPermissions($rolePermissions);
        }

        // Assign super_admin to first user
        $user = User::first();
        if ($user) {
            $user->assignRole('super_admin');
        }
    }
}
