<?php

namespace App\Services\Appointments;

use App\Events\Appointments\AppointmentCreated;
use App\Models\Appointment;
use App\Models\AppointmentSlot;
use App\Models\Branch;
use App\Models\Provider;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

/**
 * The concurrency-safe booking path the gap audit found entirely missing: the previous
 * AppointmentService::createAppointment() inserted the Appointment row unconditionally, then
 * incremented the slot's booked_count *after* the fact with no prior capacity check, no locking,
 * and no constraint — capacity could be exceeded by any number of simultaneous requests.
 *
 * Two allocation paths, both inside one DB transaction:
 *  - slot-based: row-locks the AppointmentSlot itself (it already exists, pre-generated by
 *    ScheduleGenerationService) and re-checks capacity under the lock before creating anything.
 *  - free-text/no-slot (e.g. a walk-in with no pre-generated slot): takes a locking SELECT over
 *    the exact provider+date+time key range, which — even when it matches zero rows — still
 *    acquires an InnoDB gap lock under the default REPEATABLE READ isolation, blocking a
 *    concurrent transaction from inserting a colliding row until this one commits.
 */
class AppointmentBookingService
{
    public function __construct(
        private AppointmentNumberGenerator $numberGenerator,
        private ProviderAvailabilityService $availability,
    ) {}

    public function book(array $data, User $user, bool $allowOverbooking = false): Appointment
    {
        return DB::transaction(function () use ($data, $user, $allowOverbooking) {
            $company = $user->companies()->findOrFail($data['company_id']);
            $branch = ! empty($data['branch_id']) ? Branch::find($data['branch_id']) : null;

            $slot = null;

            if (! empty($data['slot_id'])) {
                $slot = $this->lockAndValidateSlot((int) $data['slot_id'], $allowOverbooking);
                $data['provider_id'] = $data['provider_id'] ?? $slot->schedule?->provider_id;
                $data['doctor_id'] = $data['doctor_id'] ?? $slot->doctor_id;
                $data['appointment_date'] = $slot->slot_datetime->toDateString();
                $data['appointment_time'] = $slot->slot_datetime->format('H:i');
            } elseif (! empty($data['provider_id'])) {
                $this->assertNoConflict($company->id, 'provider_id', (int) $data['provider_id'], $data['appointment_date'], $data['appointment_time']);
            } elseif (! empty($data['doctor_id'])) {
                // Legacy path: no generic Provider selected, only the direct doctor_id/User
                // reference most existing callers still use. Still gap-locked the same way so
                // two concurrent requests for the same doctor/date/time can't both succeed.
                $this->assertNoConflict($company->id, 'doctor_id', (int) $data['doctor_id'], $data['appointment_date'], $data['appointment_time']);
            }

            if (! empty($data['provider_id'])) {
                $this->assertProviderBookable((int) $data['provider_id'], $data['appointment_date'], $data['appointment_time'], $slot->duration_minutes ?? 15);
            }

            $data['company_id'] = $company->id;
            $data['branch_id'] = $branch?->id ?? $data['branch_id'] ?? null;
            $data['appointment_no'] = $this->numberGenerator->generateAppointmentNumber($company);
            $data['booked_at'] = now();
            $data['status'] = 'scheduled';

            $appointment = Appointment::create($data);

            $tokenNo = $this->numberGenerator->generateTokenNumber($company, $branch);
            $appointment->token()->create([
                'company_id' => $company->id,
                'branch_id' => $appointment->branch_id,
                'token_number' => $tokenNo,
                'priority' => $data['queue_priority'] ?? 'regular',
                'generated_at' => now(),
            ]);

            if ($slot) {
                $slot->increment('booked_count');

                if ($slot->fresh()->remainingCapacity($allowOverbooking) <= 0) {
                    $slot->update(['status' => 'booked']);
                }
            }

            AppointmentCreated::dispatch($appointment);

            return $appointment->fresh(['token', 'slot', 'provider', 'patient']);
        });
    }

    /**
     * A follow-up is simply a new appointment linked via previous_appointment_id (spec §29: "this
     * is not yet a clinical follow-up decision; it is simply appointment linkage") — it goes
     * through the same booking path so it gets the same number generation, capacity checks, and
     * event dispatch as any other booking.
     */
    public function bookFollowUp(Appointment $previous, array $data, User $user): Appointment
    {
        $data['company_id'] = $previous->company_id;
        $data['branch_id'] = $data['branch_id'] ?? $previous->branch_id;
        $data['patient_id'] = $previous->patient_id;
        $data['provider_id'] = $data['provider_id'] ?? $previous->provider_id;
        $data['doctor_id'] = $data['doctor_id'] ?? $previous->doctor_id;
        $data['previous_appointment_id'] = $previous->id;
        $data['is_follow_up'] = true;
        $data['type'] = $data['type'] ?? 'followup';
        $data['source'] = $data['source'] ?? 'followup';
        $data['reason'] = $data['reason'] ?? $previous->reason;
        $data['appointment_date'] = $data['appointment_date'] ?? now()->addDays(7)->toDateString();
        $data['appointment_time'] = $data['appointment_time'] ?? $previous->appointment_time->format('H:i');

        return $this->book($data, $user);
    }

    private function lockAndValidateSlot(int $slotId, bool $allowOverbooking): AppointmentSlot
    {
        $slot = AppointmentSlot::query()->where('id', $slotId)->lockForUpdate()->first();

        if (! $slot) {
            throw ValidationException::withMessages(['slot_id' => 'The selected slot no longer exists.']);
        }

        if ($slot->status === 'blocked' || $slot->status === 'cancelled') {
            throw ValidationException::withMessages(['slot_id' => 'This slot is not bookable.']);
        }

        if (! $slot->isAvailable($allowOverbooking)) {
            throw ValidationException::withMessages(['slot_id' => 'This slot is fully booked.']);
        }

        return $slot;
    }

    private function assertNoConflict(int $companyId, string $column, int $value, string $date, string $time): void
    {
        $conflict = Appointment::query()
            ->where('company_id', $companyId)
            ->where($column, $value)
            ->where('appointment_date', $date)
            ->where('appointment_time', $time)
            ->whereNotIn('status', ['cancelled', 'no_show'])
            ->lockForUpdate()
            ->exists();

        if ($conflict) {
            throw ValidationException::withMessages(['appointment_time' => 'This provider already has an appointment at this time.']);
        }
    }

    private function assertProviderBookable(int $providerId, string $date, string $time, int $durationMinutes): void
    {
        $provider = Provider::find($providerId);

        if (! $provider) {
            return;
        }

        if (! $this->availability->isProviderBookable($provider, Carbon::parse("{$date} {$time}"), $durationMinutes)) {
            throw ValidationException::withMessages(['provider_id' => 'This provider is not available at the selected time.']);
        }
    }
}
