@extends('layouts.adminlte')

@section('page_title', 'Lab Report '.$report->report_number)

@section('page_content')
    <div class="container-fluid">
        <div class="d-flex justify-content-between align-items-center mb-4 d-print-none">
            <h2 class="mb-0">Laboratory Report</h2>
            <div class="d-flex gap-2">
                <button type="button" class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print</button>
                <a href="{{ route('admin.lab.reports.show', $report) }}" class="btn btn-outline-secondary">Back</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-start mb-3">
                    <div>
                        <h3 class="mb-1">{{ config('app.name') }}</h3>
                        <p class="text-muted mb-0">Laboratory Report</p>
                    </div>
                    <div class="text-end">
                        <p class="mb-0"><strong>Report #:</strong> {{ $report->report_number }}</p>
                        <p class="mb-0"><strong>Status:</strong> {{ strtoupper($report->status) }}</p>
                        <p class="mb-0"><strong>Date:</strong> {{ $report->generated_at?->format('Y-m-d H:i') }}</p>
                    </div>
                </div>
                <hr>
                <div class="row g-2 mb-3">
                    <div class="col-md-4"><strong>Patient:</strong> {{ $report->labOrder->patient?->full_name }}</div>
                    <div class="col-md-4"><strong>MRN:</strong> {{ $report->labOrder->patient?->enterprise_patient_no ?? $report->labOrder->patient_id }}</div>
                    <div class="col-md-4"><strong>Age/Sex:</strong> {{ $report->labOrder->patient?->date_of_birth?->diffInYears(now()) }} / {{ $report->labOrder->patient?->sex }}</div>
                    <div class="col-md-4"><strong>Encounter:</strong> {{ $report->labOrder->encounter?->encounter_no }}</div>
                    <div class="col-md-4"><strong>Referring Provider:</strong> {{ $report->labOrder->encounter?->provider?->name }}</div>
                    <div class="col-md-4"><strong>Order #:</strong> {{ $report->labOrder->order_number }}</div>
                </div>

                <table class="table table-bordered">
                    <thead>
                        <tr><th>Test</th><th class="text-end">Result</th><th>Unit</th><th>Reference Range</th><th>Flag</th></tr>
                    </thead>
                    <tbody>
                        @foreach($report->labOrder->items as $item)
                            @php($result = $item->results()->where('is_current', true)->first())
                            @if($result)
                                <tr>
                                    <td>{{ $item->test?->name }} <br><small class="text-muted">{{ $item->test?->section?->name }}</small></td>
                                    <td class="text-end">{{ $result->numeric_value ?? $result->qualitative_value ?? $result->text_value }}</td>
                                    <td>{{ $result->unit }}</td>
                                    <td>
                                        @if($result->reference_range_low !== null || $result->reference_range_high !== null)
                                            {{ $result->reference_range_low }} - {{ $result->reference_range_high }}
                                        @else
                                            {{ $result->reference_range_text }}
                                        @endif
                                    </td>
                                    <td>{{ $result->abnormal_flag && $result->abnormal_flag !== 'normal' ? strtoupper($result->abnormal_flag) : '' }}</td>
                                </tr>
                            @endif
                        @endforeach
                    </tbody>
                </table>

                <hr>
                <div class="row g-2">
                    <div class="col-md-4"><strong>Collected:</strong> {{ $report->labOrder->specimens->first()?->collected_at?->format('Y-m-d H:i') }}</div>
                    <div class="col-md-4"><strong>Report Date:</strong> {{ $report->generated_at?->format('Y-m-d H:i') }}</div>
                    <div class="col-md-4"><strong>Generated By:</strong> {{ $report->generatedBy?->name }}</div>
                </div>
            </div>
        </div>
    </div>
@stop
