@extends('layouts.adminlte')

@section('page_title', 'Lab Report — '.$report->report_number)

@section('page_content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">{{ $report->report_number }}</h3>
            <div class="card-tools">
                <span class="badge {{ $report->status === 'amended' ? 'bg-warning' : 'bg-success' }}">{{ ucfirst($report->status) }}</span>
                @can('lab.report.print')
                    <a href="{{ route('admin.lab.reports.print', $report) }}" target="_blank" class="btn btn-sm btn-secondary">Print</a>
                @endcan
            </div>
        </div>
        <div class="card-body">
            <table class="table table-sm">
                <tr><th>Order</th><td><a href="{{ route('admin.lab.orders.show', $report->labOrder) }}">{{ $report->labOrder->order_number }}</a></td></tr>
                <tr><th>Patient</th><td>{{ $report->labOrder->patient?->full_name }}</td></tr>
                <tr><th>Generated By</th><td>{{ $report->generatedBy?->name }} at {{ $report->generated_at?->format('Y-m-d H:i') }}</td></tr>
                @if($report->amended_at)
                    <tr><th>Last Amended</th><td>{{ $report->amended_at?->format('Y-m-d H:i') }}</td></tr>
                @endif
            </table>

            <h5>Results</h5>
            <table class="table table-striped">
                <thead><tr><th>Test</th><th>Result</th><th>Unit</th><th>Reference Range</th><th>Flag</th><th></th></tr></thead>
                <tbody>
                    @foreach($report->labOrder->items as $item)
                        @php($result = $item->results()->where('is_current', true)->first())
                        @if($result)
                            <tr>
                                <td>{{ $item->test?->name }} <span class="text-muted">(v{{ $result->version }})</span></td>
                                <td>{{ $result->numeric_value ?? $result->qualitative_value ?? $result->text_value }}</td>
                                <td>{{ $result->unit }}</td>
                                <td>
                                    @if($result->reference_range_low !== null || $result->reference_range_high !== null)
                                        {{ $result->reference_range_low }} - {{ $result->reference_range_high }}
                                    @else
                                        {{ $result->reference_range_text }}
                                    @endif
                                </td>
                                <td>
                                    @if($result->abnormal_flag && $result->abnormal_flag !== 'normal')
                                        <span class="badge bg-danger">{{ strtoupper($result->abnormal_flag) }}</span>
                                    @endif
                                </td>
                                <td>
                                    @can('lab.result.amend')
                                        <button type="button" class="btn btn-xs btn-warning" data-bs-toggle="modal" data-bs-target="#amend-{{ $result->id }}">Amend</button>
                                        <div class="modal fade" id="amend-{{ $result->id }}" tabindex="-1">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <form method="post" action="{{ route('admin.lab.results.amend', $result) }}">
                                                        @csrf
                                                        <div class="modal-header"><h5 class="modal-title">Amend {{ $item->test?->name }}</h5></div>
                                                        <div class="modal-body">
                                                            <label class="form-label">New Value</label>
                                                            @if(in_array($result->result_type, ['quantitative', 'semi_quantitative', 'calculated']))
                                                                <input type="number" step="0.0001" name="numeric_value" class="form-control mb-2" value="{{ $result->numeric_value }}" required>
                                                            @else
                                                                <input type="text" name="qualitative_value" class="form-control mb-2" value="{{ $result->qualitative_value ?? $result->text_value }}" required>
                                                            @endif
                                                            <label class="form-label">Reason for amendment</label>
                                                            <textarea name="reason" class="form-control" required minlength="10"></textarea>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                            <button type="submit" class="btn btn-warning">Save Amendment</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    @endcan
                                </td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop
